name: Fetch and Convert Image

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  fetch-and-convert:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 Pillow
        
    - name: Run image fetcher
      run: python fetch_and_convert_image.py
        
    - name: Commit and push if changed
      env:
        PAT: ${{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}}
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git remote set-url origin https://x-access-token:${PAT}@github.com/${{ github.repository }}
        git add img.png
        git commit -m "Update wallpaper" || exit 0
        git push