name: Fetch and Convert Image

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  fetch-and-convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
        
    - name: Set timezone
      run: |
        sudo timedatectl set-timezone Asia/Shanghai
        date
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests Pillow urllib3
        
    - name: Check environment
      run: |
        echo "Current directory: $(pwd)"
        echo "Files in directory:"
        ls -la
        echo "Python version:"
        python --version
        echo "Pip packages:"
        pip list
        
    - name: Check last run
      run: |
        if [ -f "last_run.txt" ]; then
          echo "Last run time: $(cat last_run.txt)"
        fi
        date "+%Y-%m-%d %H:%M:%S" > last_run.txt
        
    - name: Run image fetcher
      run: |
        echo "Starting image fetcher..."
        python -u fetch_and_convert_image.py
        echo "Image fetcher completed"
        
    - name: Check files before commit
      run: |
        echo "Files to be committed:"
        git status
        echo "Image file size:"
        ls -l img.jpg || echo "img.jpg not found"
        echo "Pool file size:"
        ls -l image_pool.json || echo "image_pool.json not found"
        echo "History file size:"
        ls -l used_images.txt || echo "used_images.txt not found"
        
    - name: Check file permissions
      run: |
        touch img.jpg used_images.txt image_pool.json last_run.txt
        chmod 666 img.jpg used_images.txt image_pool.json last_run.txt
        ls -la
        
    - name: Commit and push if changed
      run: |
        echo "Configuring git..."
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        
        echo "Adding files..."
        git add img.jpg used_images.txt image_pool.json last_run.txt
        
        echo "Committing changes..."
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update wallpaper"
          echo "Pushing changes..."
          git push origin HEAD:${{ github.ref }}
        fi