name: Fetch and Convert Image

on:
  schedule:
    - cron: '0 */3 * * *'  # 每三小时运行一次
  workflow_dispatch:

jobs:
  fetch_and_convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pillow

    - name: Run fetch and convert script
      run: |
        python fetch_and_convert_image.py

    - name: Upload converted image
      uses: actions/upload-artifact@v2
      with:
        name: converted-image
        path: img.png